"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { practiceService } from "../../services/practice.service";
import WeakSpotsReport from "../practice/WeakSpotsReport";

export default function PracticeSession({ kitId }) {
  const [cards, setCards] = useState([]); const [index, setIndex] = useState(0); const [revealed, setRevealed] = useState(false); const [confidence, setConfidence] = useState(3); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [weakSpots, setWeakSpots] = useState(null); const [weakSpotsLoading, setWeakSpotsLoading] = useState(true); const [weakSpotsError, setWeakSpotsError] = useState("");
  useEffect(() => { practiceService.list(kitId).then((items) => { setCards(items); return practiceService.weakSpots(kitId); }).then(setWeakSpots).catch(() => { setError("Unable to load practice cards."); setWeakSpotsError("Unable to load weak spots."); }).finally(() => { setLoading(false); setWeakSpotsLoading(false); }); }, [kitId]);
  if (loading) return <div className="animate-pulse rounded-2xl bg-white p-8"><div className="h-6 w-32 rounded bg-[#e3ebe6]" /><div className="mt-6 h-56 rounded bg-[#edf3ef]" /></div>;
  if (error) return <p role="alert" className="rounded-lg bg-[#fde8e7] p-4 text-[#a33835]">{error}</p>;
  if (!cards.length) return <><div className="rounded-2xl border border-dashed border-[#b9ccc0] bg-white p-10 text-center"><h2 className="text-xl font-bold">No flashcards yet</h2><p className="mt-2 text-[#68766f]">Complete kit generation before starting practice.</p><Link href={`/kits/${kitId}`} className="mt-5 inline-block font-bold text-[#1d5144]">Back to kit</Link></div><WeakSpotsReport data={weakSpots} loading={weakSpotsLoading} error={weakSpotsError} /></>;
  const card = cards[index];
  async function next() { setSaving(true); try { await practiceService.save(kitId, { flashcardId: card.id, confidence, covered: revealed }); setCards((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, practice: { confidence, covered: revealed } } : item)); const refreshedWeakSpots = await practiceService.weakSpots(kitId); setWeakSpots(refreshedWeakSpots); setIndex((value) => (value + 1) % cards.length); setRevealed(false); } catch (_error) { setError("Unable to save this review."); } finally { setSaving(false); } }
  return <><section className="mx-auto max-w-2xl"><div className="flex items-center justify-between text-sm font-bold text-[#68766f]"><span>Question {index + 1} / {cards.length}</span><span>{card.practice ? "Reviewed" : "Unanswered"}</span></div><article className="mt-4 rounded-2xl border border-[#d9e4dd] bg-white p-7 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-[#2f7562]">Flashcard</p><h2 className="mt-4 text-2xl font-bold leading-tight">{card.front}</h2>{revealed ? <div className="mt-8 border-t border-[#d9e4dd] pt-6"><p className="text-sm font-bold text-[#68766f]">Answer</p><p className="mt-2 leading-7 text-[#53635d]">{card.back}</p></div> : <button onClick={() => setRevealed(true)} className="mt-8 rounded-lg border border-[#2f7562] px-4 py-3 font-bold text-[#1d5144]">Reveal answer</button>}<div className="mt-8 border-t border-[#d9e4dd] pt-6"><label className="block text-sm font-bold">Confidence: {confidence}<input type="range" min="1" max="5" value={confidence} onChange={(event) => setConfidence(Number(event.target.value))} className="mt-3 w-full accent-[#2f7562]" /></label><div className="mt-5 flex justify-end"><button disabled={!revealed || saving} onClick={next} className="rounded-lg bg-[#1d5144] px-5 py-3 font-bold text-white disabled:opacity-50">{saving ? "Saving..." : "Next"}</button></div></div></article></section><WeakSpotsReport data={weakSpots} loading={weakSpotsLoading} error={weakSpotsError} /></>;
}