import Link from "next/link";
import Footer from "../components/common/Footer";

const steps = [
  { number: "01", title: "Research", text: "Turn the company and role into grounded context you can actually use." },
  { number: "02", title: "Prepare", text: "Connect requirements to focused questions, answer outlines, and flashcards." },
  { number: "03", title: "Practice", text: "Build confidence deliberately and see what deserves your attention next." },
];

export default function Home() {
  return <div className="min-h-screen bg-[var(--canvas)] text-[var(--ink)]">
    <header className="border-b border-[var(--line)] bg-[var(--canvas)]/90"><div className="page-container flex items-center justify-between py-5"><Link href="/" className="brand-mark">AI<span>Prep</span></Link><nav className="hidden items-center gap-7 text-sm font-bold text-[var(--muted)] sm:flex"><a href="#workflow" className="hover:text-[var(--ink)]">How it works</a><a href="#coverage" className="hover:text-[var(--ink)]">Coverage</a><Link href="/login" className="hover:text-[var(--ink)]">Sign in</Link></nav><Link href="/kits/new" className="button button-primary">Build a kit</Link></div></header>
    <main>
      <section className="page-container grid min-h-[620px] items-center gap-12 py-16 lg:grid-cols-[1.15fr_0.85fr] lg:py-24"><div className="page-enter"><p className="eyebrow">A sharper way to prepare</p><h1 className="mt-5 max-w-3xl text-5xl font-black leading-[1.02] tracking-[-0.06em] sm:text-7xl">Walk into the interview with a plan.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[var(--muted)]">AI Interview Prep Kit turns a job description into a research-backed workspace for questions, flashcards, practice, and the weak spots worth fixing next.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/kits/new" className="button button-primary px-5">Build your interview kit <span className="ml-2">→</span></Link><Link href="/dashboard" className="button button-secondary px-5">Explore dashboard</Link></div><p className="mt-5 text-xs font-semibold text-[var(--muted)]">No fake metrics. Just a clearer preparation loop.</p></div><div className="relative page-enter"><div className="surface relative overflow-hidden p-5 sm:p-7"><div className="flex items-center justify-between border-b border-[var(--line)] pb-5"><div><p className="eyebrow">Preparation signal</p><h2 className="mt-2 text-xl font-bold">Senior Frontend Engineer</h2></div><span className="rounded-full bg-[var(--brand-soft)] px-3 py-1 text-xs font-bold text-[var(--brand)]">In progress</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-[var(--surface-muted)] p-4"><p className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Coverage</p><p className="mt-3 text-3xl font-black text-[var(--brand)]">82%</p><div className="mt-3 h-2 rounded-full bg-white"><div className="h-full w-[82%] rounded-full bg-[var(--brand)]" /></div></div><div className="rounded-xl bg-[#fff1d9] p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#8a5a00]">Focus tomorrow</p><p className="mt-3 text-lg font-bold text-[#704b12]">System design</p><p className="mt-1 text-xs text-[#8a5a00]">Lowest confidence area</p></div></div><div className="mt-5 rounded-xl border border-[var(--line)] p-4"><div className="flex items-center justify-between"><p className="font-bold">Practice queue</p><span className="text-xs font-bold text-[var(--muted)]">4 cards ready</span></div><div className="mt-4 space-y-3">{["Design a resilient API", "Explain event delegation", "Tell me about a tradeoff"].map((item, index) => <div key={item} className="flex items-center gap-3 text-sm"><span className={`h-2.5 w-2.5 rounded-full ${index === 0 ? "bg-[#d28b45]" : "bg-[#8fc09e]"}`} /><span className="text-[var(--muted)]">{item}</span></div>)}</div></div></div></div></section>
      <section id="workflow" className="border-y border-[var(--line)] bg-white"><div className="page-container py-20"><div className="section-heading"><div><p className="eyebrow">The preparation loop</p><h2 className="mt-2 text-3xl font-bold tracking-tight">From scattered notes to a focused next step.</h2></div><p className="max-w-sm text-sm leading-6 text-[var(--muted)]">Every surface is connected to the role requirements, so your time goes where it matters.</p></div><div className="stagger mt-12 grid gap-4 md:grid-cols-3">{steps.map((step) => <article key={step.number} className="rounded-2xl border border-[var(--line)] bg-[var(--canvas)] p-6"><span className="text-sm font-black text-[var(--accent)]">{step.number}</span><h3 className="mt-12 text-xl font-bold">{step.title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{step.text}</p></article>)}</div></div></section>
      <section id="coverage" className="page-container grid gap-12 py-20 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="eyebrow">Requirement coverage</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Know what you know. See what still needs work.</h2><p className="mt-5 leading-7 text-[var(--muted)]">Practice confidence is connected back to the skills and topics in your role. Your weak spots report keeps tomorrow’s focus concrete and honest.</p><Link href="/kits/new" className="button button-secondary mt-7">Start with a job description →</Link></div><div className="surface grid gap-4 p-6 sm:grid-cols-2"><div className="rounded-xl bg-[var(--surface-muted)] p-5"><p className="eyebrow">Questions</p><p className="mt-3 text-4xl font-black">4</p><p className="mt-2 text-sm text-[var(--muted)]">distinct interview angles</p></div><div className="rounded-xl bg-[#fff1d9] p-5"><p className="text-xs font-black uppercase tracking-wider text-[#8a5a00]">Weak spot</p><p className="mt-3 text-2xl font-black text-[#704b12]">AWS</p><p className="mt-2 text-sm text-[#8a5a00]">30% confidence</p></div><div className="rounded-xl border border-[var(--line)] p-5 sm:col-span-2"><p className="font-bold">Focus tomorrow</p><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full bg-[var(--brand-soft)] px-3 py-1 text-sm font-bold text-[var(--brand)]">AWS</span><span className="rounded-full bg-[var(--brand-soft)] px-3 py-1 text-sm font-bold text-[var(--brand)]">System design</span></div></div></div></section>
      <section className="page-container pb-20"><div className="rounded-3xl bg-[var(--brand)] px-7 py-12 text-white sm:px-12"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#bde1cb]">Ready when you are</p><div className="mt-4 flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><div><h2 className="max-w-xl text-3xl font-black tracking-tight sm:text-4xl">Make your next hour of prep count.</h2><p className="mt-4 max-w-lg leading-7 text-[#d7eee0]">Start with the role, then let the workspace keep the plan visible.</p></div><Link href="/kits/new" className="button bg-white text-[var(--brand)] hover:bg-[#eef8f0]">Build your kit →</Link></div></div></section>
    </main><Footer />
  </div>;
}