"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { authService } from "../../services/auth.service";

export default function RegisterPage() {
  const router = useRouter();
  const [form, setForm] = useState({ email: "", password: "", confirm: "" });
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event) { event.preventDefault(); setError(""); if (form.password.length < 8 || form.password !== form.confirm) return setError("Use a password of at least 8 characters and confirm it exactly."); setBusy(true); try { await authService.register({ email: form.email, password: form.password }); router.replace("/dashboard"); } catch (err) { setError(err.response?.data?.message || "Unable to create account."); setBusy(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-[#f4f7f5] px-5 py-12"><div className="w-full max-w-md rounded-2xl border border-[#d9e4dd] bg-white p-8 shadow-sm"><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#2f7562]">AI Interview Prep Kit</p><h1 className="mt-6 text-3xl font-bold">Create your workspace</h1><p className="mt-2 text-[#68766f]">Keep your preparation organized from first research to final practice.</p><form onSubmit={submit} className="mt-8 space-y-5"><label className="block text-sm font-bold">Email<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="mt-2 w-full rounded-lg border border-[#c8d6ce] px-3 py-3 font-normal outline-none focus:border-[#2f7562]" /></label><label className="block text-sm font-bold">Password<input required minLength={8} type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} className="mt-2 w-full rounded-lg border border-[#c8d6ce] px-3 py-3 font-normal outline-none focus:border-[#2f7562]" /></label><label className="block text-sm font-bold">Confirm password<input required minLength={8} type="password" value={form.confirm} onChange={(event) => setForm({ ...form, confirm: event.target.value })} className="mt-2 w-full rounded-lg border border-[#c8d6ce] px-3 py-3 font-normal outline-none focus:border-[#2f7562]" /></label>{error && <p role="alert" className="rounded-lg bg-[#fde8e7] px-3 py-2 text-sm text-[#a33835]">{error}</p>}<button disabled={busy} className="w-full rounded-lg bg-[#1d5144] px-4 py-3 font-bold text-white disabled:opacity-60">{busy ? "Creating..." : "Create account"}</button></form><p className="mt-6 text-sm text-[#68766f]">Already have an account? <Link className="font-bold text-[#1d5144]" href="/login">Sign in</Link></p></div></main>;
}