"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { authService } from "../../services/auth.service";
import AuthFrame from "../../components/common/AuthFrame";

export default function RegisterPage() {
  const router = useRouter();
  const [form, setForm] = useState({ email: "", password: "", confirm: "" });
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event) { event.preventDefault(); setError(""); if (form.password.length < 8 || form.password !== form.confirm) return setError("Use a password of at least 8 characters and confirm it exactly."); setBusy(true); try { await authService.register({ email: form.email, password: form.password }); router.replace("/dashboard"); } catch (err) { setError(err.response?.data?.message || "Unable to create account."); setBusy(false); } }
  return <AuthFrame><div className="page-container grid min-h-[620px] items-center gap-12 py-12 lg:grid-cols-[0.9fr_1.1fr]"><div className="hidden rounded-3xl bg-[#fff1d9] p-10 lg:block"><p className="eyebrow text-[#8a5a00]">Start with intention</p><h1 className="mt-6 text-4xl font-black tracking-tight text-[#704b12]">Turn preparation into progress.</h1><p className="mt-5 leading-7 text-[#8a5a00]">Build a repeatable loop around the role you actually want.</p><div className="mt-12 rounded-2xl bg-white/70 p-5 text-sm text-[#704b12]"><p className="font-bold">Your workspace will connect</p><p className="mt-2">Research · Questions · Flashcards · Practice</p></div></div><div className="surface mx-auto w-full max-w-md p-7 sm:p-9"><p className="eyebrow">Create your workspace</p><h1 className="mt-3 text-3xl font-bold">Start with AI Prep</h1><p className="mt-2 text-[var(--muted)]">Keep your preparation organized from first research to final practice.</p><form onSubmit={submit} className="mt-8 space-y-5"><label className="field-label">Email<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="field-input" /></label><label className="field-label">Password<input required minLength={8} type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} className="field-input" /></label><label className="field-label">Confirm password<input required minLength={8} type="password" value={form.confirm} onChange={(event) => setForm({ ...form, confirm: event.target.value })} className="field-input" /></label>{error && <p role="alert" className="rounded-lg bg-[#fbe9e7] px-3 py-2 text-sm text-[var(--danger)]">{error}</p>}<button disabled={busy} className="button button-primary w-full">{busy ? "Creating..." : "Create account"}</button></form><p className="mt-6 text-sm text-[var(--muted)]">Already have an account? <Link className="font-bold text-[var(--brand)]" href="/login">Sign in</Link></p></div></div></AuthFrame>;
}